
replicaCount: 1
restartPolicy: Never

# Evaluated by the post-install hook
sleepyTime: "10"

index: >-
  <h1>Hello</h1>
  <p>This is a test</p>

log-server:
  name: trillian-log-server
  image:
    repository: gcr.io/dazwilkin-180601-trillian/log-server
    tag: 8e4c86bfbbfbee4ad65c3d03808814051323d500
    pullPolicy: IfNotPresent
  service:
    annotations: {}
    clusterIP: ""
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
    port: 8888
    nodePort: ""
  podAnnotations: {}
  resources: {}
  nodeSelector: {}

prometheus:
  name: prometheus-to-sd
  image:
    repository: gcr.io/google-containers/prometheus-to-sd
    tag: v0.2.6