apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  STORAGE_SYSTEM: cloud_spanner
  STORAGE_FLAG: --cloudspanner_uri=projects/{{ .Values.gcp.project.id }}/instances/{{ .Values.gcp.project.spanner.instance }}/databases/{{ .Values.gcp.project.spanner.database }}
  GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google/key.json
  SIGNER_DEQUEUE_BUCKET_FRACTION: "0.0078"
  SIGNER_BATCH_SIZE: "1800"
  SIGNER_INTERVAL: "2ms"
  SIGNER_NUM_SEQUENCERS: "10"
  SIGNER_RESIGN_ODDS: "1000"
